baseURL = "https://www.codemonkey.space/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Code monkey in space"
# Change the default theme to be use when building the site with Hugo
theme = "uBlogger"

[params]
  # uBlogger theme version
  version = "1.3.X"
  mainSections = ["posts"]
  keywords = [".netcore", "software development", "datatent", "database"]
  gitRepo = "https://github.com/sebfischer83/codemonkey"
[params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

[params.header.title]
    typeit = false
    # URL of the LOGO
    logo = ""
    # title name
    name = "Code monkey in space"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""

 # Footer config
  [params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    # Site creation time
    since = 2021
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
[params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = "sebfischer@gmx.net"
      title = ""
      # subtitle shown in home page
      subtitle = "This is My New Hugo Site"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      disclaimer = ""

  [params.social]
    GitHub = "sebfischer83"
    Linkedin = ""
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Email = "sebfischer@gmx.net"
    RSS = true # 

[params.page]
    fraction = true
    ruby = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = false

[params.summary.tags]
    theme = "image"
    color = "white"
    background = "black"
    transparency = 0.9

[params.cookieconsent]
    enable = true
[params.cookieconsent.content]
    message = "sdfsdf"
    dismiss = "gffgh"
    link = "dfdfgdfg"

[author]
  name = "sf.en"

[params.page.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true

[params.page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = true
    Pinterest = false
    Tumblr = false
    HackerNews = false
    Reddit = false
    VK = false
    Buffer = false
    Xing = false
    Line = true
    Instapaper = false
    Pocket = false
    Digg = false
    Stumbleupon = false
    Flipboard = false
    Weibo = true
    Renren = false
    Myspace = true
    Blogger = true
    Baidu = false
    Odnoklassniki = false
    Evernote = true
    Skype = false
    Trello = false
    Mix = false

[params.page.code]
    # whether to show the copy button of the code block
    copy = true
    # the maximum number of lines of displayed code by default
    maxShownLines = 10

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "impressum"
    pre = ""
    post = ""
    name = "Impressum"
    url = "/impressum/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "privacy"
    pre = ""
    post = ""
    name = "Privacy"
    url = "/privacy/"
    title = ""
    weight = 5

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false